<?php $this->headTitle('Корзина покупателя');?>
<div class="carttitle"><h1>Корзина покупателя</h1></div>
<div class="wishes">Уважаемый покупатель, мы очень рады, что вы воспользовались услугами нашего интернет-магазина. Если вы уже определились c выбором, пожалуйста, помогите определиться и другим посетителям, оставьте отзывы на приобретаемые товары. Большое спасибо.</div>
<div align="center">
           <div style="width:940px">
             <script type="text/javascript">
              var myShopPartnerId = '3741_3';
              var myShopExternalCSS = '';
              var myShopClearCartURL = '';
              var str = location;
              document.write('<scr'+'ipt type="text/javascript" charset="windows-1251" src="http://p.my-shop.ru/order?form=JS_embed&partner='+myShopPartnerId+'&'+location.search.substring(1)+(myShopExternalCSS?'&extcss='+encodeURIComponent(myShopExternalCSS):'')+(myShopClearCartURL?'&clearcart='+encodeURIComponent(myShopClearCartURL):'')+'&nocache='+Math.ceil(Math.random()*1000000)+'"></sc'+'ript>');
             </script>
           </div>
          </div>

<script>
 $("#myShopOrderIframe").css("height","2000px");
</script>