<?php $this->headTitle('Корзина покупателя');?>
<div class="carttitle"><h1>Корзина покупателя</h1></div>
<div class="wishes">Уважаемый покупатель, мы очень рады, что вы воспользовались услугами нашего интернет-магазина. Если вы уже определились c выбором, пожалуйста, помогите определиться и другим посетителям, оставьте отзывы на приобретаемые товары. Большое спасибо.</div>
<div align="center">
           <div style="width:940px">
            <script type="text/javascript">
              var myShopPartnerId = '<?php echo PARTNER;?>';
              var myShopClearCartURL = '';
              var myShopColor1 = '#FFFFFF';
              document.write('<scr'+'ipt type="text/javascript" src="https://my-shop.ru/embed?q=order&partner_id='+myShopPartnerId+'&'+location.search.substring(1)+'&clearcart='+encodeURIComponent(myShopClearCartURL)+'&color1='+encodeURIComponent(myShopColor1)+'&nocache='+Math.ceil(Math.random()*1000000)+'"></sc'+'ript>');
            </script>
           </div>
          </div>

<script>
 $("#myShopOrderIframe").css("height","2000px");
</script>