<?php $this->headMeta()->setName('description',DESC);?>
<?php $this->headTitle($this->curcat['name']);?>
<div class="products_all">
    <?php
        $pp = array('cat'=>$this->category,'section'=>$this->section);
        echo $this->action('categorylegend','categories',null,$pp);
    ?>
    <div class="products_all_caption">
        <div class="pa_caption_name left"><h1><?php echo $this->curcat['name'];?></h1></div>
        <div class="clear"></div>
    </div>
<?php if ($this->countnews>0):?>   
<?php foreach($this->news as $key => $val):?>
 <div class="prods_part">
     <div class="prods_part_caption">
         <div class="left">
            <h2><?php echo $val['name'];?></h2>
         </div>
         <div class="prods_part_postfix left">
            <a rel="nofollow" href="<?php echo $this->url(array('controller'=>'categories','action'=>'catlist','section'=>$this->section,'cat'=>$key),null,true);?>" title="<?php echo glob_quoteStr($val['name']);?>">посмотреть все товары категории</a>
         </div>
         <div class="clear"></div>
     </div>
  <div class="prods_items_list">
   <?php foreach($val['products'] as $key2=>$val2):?>
    <div class="prods_item">
     <div class="prod_info">
     <?php $url = $this->url(array('controller'=>'products','action'=>'getdetails','item'=>$val2['translit']),null,true);?>
     <?php $pic = ($val2['picture']==''?'/images/nopic.png':$val2['picture']);?>
     <div class="prod_name"><a href="<?php echo $url;?>" title="<?php echo glob_quoteStr($val2['name']);?>"><?php echo $val2['name']?></a></div>
      <div class="prod_img">
          <a href="<?php echo $url;?>"><img width="120" onload="resizeme($(this));" alt="<?php echo glob_quoteStr($val2['name']);?>" src="<?php echo $pic;?>"></a>
      </div>
      <div class="prod_details">
          <?php echo glob_productInfoFormat2("author", $val2['author']);?>
          <?php echo glob_productInfoFormat2("producer", $val2['producer']);?>
          <?php echo glob_productInfoFormat2("pages", $val2['pages'],"стр.");?>
          <?php echo glob_productInfoFormat2("year", $val2['year'], "г.");?>
      </div>
     </div>
     <div class="prod_price_c">
      <div class="prod_price2"><?php echo $val2['price']." руб.";?></div>
      <div class="prod_btns">
        <div class="btnBuy_d"><button class="btnBuy" onclick="<?php echo 'buyFromCat('.($val2['link_ID']==0?$val2['id']:$val2['link_ID']).',$(this))';?>">В корзину</button></div>
        <input type="hidden" class="holdprodid" value="<?php echo $val2['id'];?>">
        <input type="hidden" class="linkid" value="<?php echo ($val2['link_ID']==0?$val2['id']:$val2['link_ID']);?>">
      </div>
     </div>
    </div>
   <?php endforeach;?>
  </div>
 </div>
<?php endforeach;?>
  <iframe name="cartdetailframe" id="cartdetailframe" frameborder="no" width="0" height="0" src="<?php echo DOMAIN_PATH.'/application/views/scripts/cartFrame.html';?>">
  </iframe>    
<?php elseif($this->countnews==0): ?>
    <div class="prducts_no_product">Упс... Здесь все товары проданы</div>
<?php endif;?>
    
</div>