<footer>
<div class="bottom">
 <div class="bottom_copyright">
  <div class="counter left">
  <!--LiveInternet counter--><script type="text/javascript">
  document.write("<a href='http://www.liveinternet.ru/click' "+
  "target=_blank><img src='//counter.yadro.ru/hit?t44.1;r"+
  escape(document.referrer)+((typeof(screen)=="undefined")?"":
  ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
  screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
  ";"+Math.random()+
  "' alt='' title='LiveInternet' "+
  "border='0' width='31' height='31'><\/a>")
  </script><!--/LiveInternet-->
  </div>
  <div class="counter left">
  <script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2390318"></script>
     <noscript>
      <a href="http://top100.rambler.ru/navi/2390318/">
     <img src="http://counter.rambler.ru/top100.cnt?2390318" alt="Rambler's Top100" border="0" />
     </a>

    </noscript>
  </div>
  <div class="counter left">
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
(function(w,n,d,r,s){d.write('<div><a href="http://top.mail.ru/jump?from=2326269"><img src="'+
('https:'==d.location.protocol?'https:':'http:')+'//top-fwz1.mail.ru/counter?id=2326269;t=216;js=13'+
((r=d.referrer)?';r='+escape(r):'')+((s=w.screen)?';s='+s.width+'*'+s.height:'')+';_='+Math.random()+
'" style="border:0;" height="31" width="88" alt="–ейтинг@Mail.ru" /><\/a><\/div>');})(window,navigator,document);//]]>
</script><noscript><div><a href="http://top.mail.ru/jump?from=2326269">
<img src="//top-fwz1.mail.ru/counter?id=2326269;t=216;js=na" style="border:0;"
height="31" width="88" alt="–ейтинг@Mail.ru" /></a></div></noscript>
<!-- //Rating@Mail.ru counter -->

  </div>
  <div class="counter left">
   <a href="http://www.kids-price.ru"><img height="31" width="88" alt="Kids-Price.Ru - цены на детские товары, кол€ски, автомобильные детские кресла, одежду и обувь." src="http://www.kids-price.ru/i/banner5.gif" border="0" /></a>
  </div>
  <div class="copyright right">&#169 2011-<?php echo date('Y');?> »нтернет-магазин учебников и учебных принадлежностей ychebniki.ru</div>
  <div class="clear"></div>
 </div>
</div>
</footer>