<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=windows-1251');

$this->headMeta()->setName('keywords','учебники,учебные пособия,школьные принадлежности,канцтовары,рюкзаки,ранцы,офисные программы');
$this->headTitle()->setSeparator(' | ');
$this->headTitle('Учебники.Ру - Интернет-магазин учебников и учебных принадлежностей. Купить учебники, канцтовары, школьные рюкзаки.');
$this->headLink()->appendStylesheet('/styles/styles.css');
//$this->headLink()->appendStylesheet('/styles/jquery.autocomplete.css');
$this->headLink(array('rel' => 'shortcut icon','href' => '/images/favicon.ico'),'PREPEND');
$this->headScript()->appendFile('/js/jquery-1.3.2.min.js');
$this->headScript()->appendFile('/js/jquery.autocomplete.js');
$this->headScript()->appendFile('/js/jquery.cookie.js');
$this->headScript()->appendFile('/js/myjs.js');

echo $this->doctype('HTML5'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" >
    <head>
        <?php echo $this->headMeta();?>
        <?php echo $this->headTitle();?>
        <?php echo $this->headLink();?>
        <?php echo $this->headScript();?>
    </head>