
<div class="left_column left">
<nav>
 <?php echo $this->action('index','categories');?>
</nav>
 <?php echo $this->action('holds','holdlist');?>

 <!-- VK Widget -->

<div id="vk_groups"></div>
 <!-- expresspokupka-->
 <div class="express_all">
 <div id="expokpart3166"></div>
 <script type="text/javascript">
 var expokpartid = 3166;
 </script>
 <script src="http://www.expresspokupka.ru/javascripts/partner/partner.js" type="text/javascript"></script>
 </div>
 <!------------------->
 
 <!--<div class="my_banner" id="my_sport_landia_banner" style="display:none;">
  <script>getSportLandiaBanner();</script>
 </div>-->
 
</div>