<div class="comments_form">
  <div class="cf_caption">Представьтесь пожалуйста:</div>
  <div class="cf_name"><input type="text" name="uname" id="uname"></div>
  <div class="cf_comment"><textarea resize="false" name="comment" id="ucomment" rows="5" cols="40"></textarea></div>
  <div class="cf_btn"><input type="button" name="commentApply" id="commentApply" value="Оставить отзыв" onclick="addComment(<?php echo $this->item;?>);"></div>
</div>