<?php $this->headTitle('Контактная информация');?>
<div class="addinfo">
<div class="addinfo_title"><h1>Контактная информация</h1></div>
<div class="addinfo_caution"><u><b>Внимание!!!</b></u> Данный магазин является партнером My-shop.ru. Более полная контактная информация доступна на <a href="http://my-shop.ru/?partner=3741">My-shop.ru</a></div>
Телефоны My-shop.ru:
<ul>
 <li>(495) 638-53-38 - для Москвы</li>
 <li>8 (800) 100-53-38 - для РФ (бесплатно)</li>
</ul>
многоканальный; понедельник-пятница - 9:00-21:00, суббота-воскресенье - 10:00-19:00

<div>Так же задать вопрос можно:</div>
<ul>
 <li id="infoMail">E-mail: <script> $("#infoMail").append('<a href="mailto:info@ychebniki.ru">info@ychebniki.ru</a>'); </script></li>
 <li>Мы Вконтакте: <a href="http://vk.com/y4ebniki">http://vk.com/y4ebniki</a></li>
</ul>

</div>