<?php $this->headTitle('Способы оплаты');?>
<div class="addinfo">
<div class="addinfo_title"><h1>Информация о способах оплаты</h1></div>
 <TABLE border="0" cellspacing="2" cellpadding="2">
  <tr>
   <?php echo $this->payment;?>
  </tr>
 </TABLE>
 <div class="addinfo_caution"><u><b>Внимание!!!</b></u> Данный магазин является партнером My-shop.ru. Более полная информация об оплате доступна на <a href="http://my-shop.ru/?partner=3741">My-shop.ru</a></div>
</div>